package ru.mail.colloquium.diagnostics.statistics;

public enum StatAction {
    AddAddress,
    EditAddress,
    Addresses,
    Logout,
    Avatar,
    Suggest,
    Favorite,
    JoinGroup,
    ShareGroup,
    Request,
    Confirm,
    Cancel,
    Retry,
    Photo,
    TutorialBack,
    TutorialClose,
    Buy,
    BuyAlone,
    BuyTogether,
    BuyJoin,
    Description,
    GroupsAll,
    OpenGroup,
    Merchant,
    LikeMerchant,
    Outside,
    Good,
    ErrorButton,
    ChooseAddress,
    Menu,
    Submit,
    ViewAvatar,
    TakePhoto,
    Gallery,
    AddCard,
    Close,
    Close2,
    Telegram,
    Ok,
    Viber,
    Vk,
    Whatsapp,
    Share,
    Login,
    EditProfile,
    Favorites,
    Cards,
    Settings,
    Support,
    ChooseCard,
    CreateOrder,
    Delete,
    AllRelated,
    AllRecommended,
    Next1,
    Next2,
    Next3,
    NextN,
    Card,
    JoinGroup2,
    Page,
    ForceConfirm,
    Order,
    State,
    Save,
    Search,
    Edit,
    DeleteConfirm,
    Plus,
    Quantity,
    Size,
    Color,
    EditFeedback,
    InviteFriends,
    Share2,
    Copy,
    Back,
    Link,
    ConfirmReceipt,

    Send,
    Sort,
    AddPhoto,
    Subcategory,
    Subcategories,
    Tracking,

    Badge, Feedback;


    public static StatAction next(int currentItem) {
        switch (currentItem) {
            case 0:
                return Next1;
            case 1:
                return Next2;
            case 2:
                return Next3;
        }
        return NextN;
    }
}
